royaloperahouse/stream-tv-app

src/components/SettingsComponents/components/SignOut.tsx
src/configs/apiConfig.ts
src/services/apiClient/index.ts

**What?**
unpair app on the backend side
**Why?**
To complete task #15, unpair the app on the backend side too.
**How?**
has been added method unLink

#15 added method for unpair app on the backend side

---

ios/Podfile.lock
src/components/EventDetailsComponents/components/General.tsx
src/components/EventListComponents/components/RailSections.tsx
src/components/GlobalModal/index.tsx
src/components/GlobalModal/variants/continueWatchingModal.tsx
src/components/GlobalModal/variants/index.tsx
src/components/WithBackground.tsx
src/configs/bitMovinPlayerConfig.ts
src/hooks/useContinueWatchingList.tsx
src/screens/EventDetailsScreen/index.tsx
src/screens/HomePageScreen/index.tsx
src/services/bitMovinPlayer/index.ts
src/services/store/events/Selectors.ts
src/services/types/bitmovinPlayer.ts
src/services/types/globalModal.ts
src/services/types/models.ts
yarn.lock

**What?**
Added ability to continue watching video #35 
**Why?**
App provides the ability to choose between resume playing from the finishing point(if a user has been already started watching the video) or watching from the beginning;
**How?**
Saving time points of videos to AsyncStorage(will work for FireStick); if a user has early saved time`s point then before opening  video player, the app shows the modal screen with choosing between a resume play video  or start again
if a user has saved time points then "continue watching" rail of events appears  
**How to test?**
Open a video, start watching the video and stop it at some time point. close player and try to open again

#35 added ability to continue watching video

---

android/app/src/main/java/com/rohtvapp/ROHBitMovinPlayerPackage/PlayerContainerView.java
ios/Podfile.lock
src/components/EventDetailsComponents/components/General.tsx
src/components/GlobalModal/variants/errorModal.tsx
src/components/GlobalModal/variants/index.tsx
src/components/Player/index.tsx
src/screens/EventDetailsScreen/index.tsx
src/services/types/bitmovinPlayer.ts
yarn.lock

**What?**
added the Error Page for Bitmovin player errors  and getting Akamai manifest errors #59 
Why?
it will be useful for debugging and friendly and informational for users
How?
has been added the Error modal page, and it has been plugged in bitmovin player(EventDetails screen) and General section of EventDetails screen when we get Akamai manifest URL of videos
How to test?
if the video  player throws an Error Exception then we will see a screen with an error warning

added the Error Page for Bitmovin player errors

---

src/components/Player/ControlButton.tsx
src/components/Player/PlayerControls.tsx
src/components/Player/index.tsx

What?
#56  fixed bug with loses focus when the control panel is disappearing.
Why?
any user doesn`t need to double click on the remote control to get focus on some button of the control panel.  position of a previously focused element  saved when the control panel has appeared;
How?
has been changed queue of calling of animation;
How to test?
Open some video and try to switch between control buttons of the control panel;  press on some buttons, look to how the control panel will appear and disappear;

#56 fixed bug with playing and stopping video

---

src/components/EventDetailsComponents/components/General.tsx

**What?**
#91 Correct title of performance from Prismic 
set the correct title of videos from Prismic
**Why?**
**How?**
passed right data to the Bitmovin player component in the General section of the Event details screen
**How to test?**
compare data on backend said with showing data of the Bimovin player in the app

#91 set correct title of videos from Prismic

---

src/hooks/useMyList.tsx

#115 Problem with MyList; updating the state of the already unmounted component
What? 
appearing error when user moving on navigation menu much quickly

fix problem with updating already unmounted component in myList

---

src/components/EventListComponents/components/RailSections.tsx
src/components/NavMenu/index.tsx
src/screens/EventDetailsScreen/index.tsx

What?
#116 
fixed  bug with rails when updating animation of scrolling on unmounted screen threw the error

fixed  bug wit rails 

---

src/components/EventDetailsComponents/commonControls/ActionButtonList.tsx
src/components/EventDetailsComponents/commonControls/ExpandableButton.tsx
src/components/EventDetailsComponents/components/General.tsx
src/components/Player/PlayerControls.tsx

#113 Pause/play buttons don't work on the remote control

added play and pause handling of video on remote control

---

src/components/VirtualKeyboard/index.tsx

What? 
#134 Removed Russian language from the search screen
How?
removed locale of the virtual keyboard(VirualKeybord component)

Removed russian language from search screen

---

App.tsx
src/layouts/contentLayout.tsx
src/layouts/mainLayout.tsx

What? #140 has been hidden of live stream option in the main menu, by using a feature flag

hidden of live stream option in main menu, by using feature flag

---

src/components/EventDetailsComponents/components/Cast.tsx
src/components/EventDetailsComponents/components/Creatives.tsx
src/services/types/models.ts

What?
#133 Correct Data: Get Cast and Creatives from Diese
the section will be hidden if it has no data for render

cast-and-creatives-from-diese

---

src/components/EventListComponents/components/DigitalEventItem.tsx
src/components/GoBack.tsx
src/components/NavMenu/index.tsx
src/screens/BalletDanceScreen/index.tsx
src/screens/HomePageScreen/index.tsx
src/screens/MyListScreen/index.tsx
src/screens/OperaMusicScreen/index.tsx

What? 
#124 fixed problem with navigation on nav menu, if the content is empty
often we could see this behavior on the My List screen if we removed all added items from my list and returned to the main layout again.

fixed problem with navigation on nav menu, if content is empty

---

android/app/src/main/java/com/rohtvapp/ROHBitMovinPlayerPackage/PlayerContainerView.java

What?
#159 added manual playback config to bitmovin player;
enabled tunneled playback;
How?
improved PlayerContainerView.java file

added manual playback config to bitmovin player

---

src/services/store/events/Sagas.ts
src/services/types/models.ts

What?
#157 changed getting tags for events grouping

changed getting tags for events grouping

---

App.tsx
src/components/NavMenu/index.tsx

What?
#152 improved return button functionality and side menu
Rule 1: On the home screen, the return button opens up the side-nav menu
Rule 2: The return button does not exit the app - only the home button does that
Rule 3: The return button on an item page will return the user back to the home screen.

improved return button functionality and side menu

---

src/components/Player/PlayerControls.tsx

What?
#148  added event handlers for fastForward and rewind buttons of Remote Control

add event handlers for fastForward and rewind buttons of RC

---

src/screens/MyListScreen/index.tsx

#164 improved layout if my list

improved layout if my list

---

src/configs/prismicApiConfig.ts
src/services/apiClient/index.ts

#156  changed to production environments of Prismic and Rest API

changed to production environments of Prismic and Rest API

---

src/components/EventDetailsComponents/components/General.tsx
src/components/EventListComponents/components/DigitalEventItem.tsx
src/components/EventListComponents/components/Preview.tsx
src/components/SearchResult.tsx
src/configs/fuseConfig.ts

#168 Changed digital Event Details data source for TV app titles

Digital Event Details data source for TV app titles

---

src/components/EventDetailsComponents/commonControls/ActionButtonList.tsx
src/components/EventDetailsComponents/components/General.tsx
src/services/store/events/Sagas.ts

#130 Hiding watch trailer button if trailer not found for an event

hide watch trailer button if an event has no trailers

---

src/components/EventListComponents/components/DigitalEventItem.tsx
src/components/EventListComponents/components/Preview.tsx
src/screens/BalletDanceScreen/index.tsx
src/screens/HomePageScreen/index.tsx
src/screens/OperaMusicScreen/index.tsx

#165 added title of a category to events for HomePage, Ballet & Dance, Opera & Music screens

Missing category

---

src/components/EventDetailsComponents/components/General.tsx
src/components/EventListComponents/components/DigitalEventItem.tsx
src/components/EventListComponents/components/Preview.tsx
src/components/SearchResult.tsx
src/services/types/models.ts

#174  change source URL for images as rails, previews of events, and so on.

change source url for images

---

src/services/store/events/Selectors.ts

#169  fixed sorting events by subtags

fixed sorting events by subtags

---

src/components/EventDetailsComponents/components/General.tsx
src/components/EventListComponents/components/Preview.tsx
src/components/SearchResult.tsx
src/services/types/models.ts

#178  fixed correct data(description and short description) from prismic

fixed correct data(description and short description) from prismic

---

src/configs/settingsConfig.ts
src/services/apiClient/index.ts

#155  switched subscription`s managing to the backend

switch subscription`s managing to the backend

---

src/components/EventDetailsComponents/commonControls/MultiColumnRoleNameList.tsx
src/components/EventDetailsComponents/commonControls/MultiColumnSynopsisList.tsx
src/components/EventDetailsComponents/components/Synopsis.tsx
src/components/ScrollingArrowPagination.tsx
src/hooks/useSplitingOnColumnsForSynopsis.tsx
src/services/types/models.ts

#177  created multi-page component for showing synopsis with a lot of paragraphs; changed data for synopsis

create multi-page component for showing synopsis

---

src/components/EventDetailsComponents/components/General.tsx
src/components/EventListComponents/components/DigitalEventItem.tsx
src/components/EventListComponents/components/Preview.tsx
src/components/SearchResult.tsx

#182  fixed resolution of images from prismic

fix resolution of images from prismic

---

src/components/SettingsComponents/components/AppVersion.tsx
src/components/SettingsComponents/index.tsx
src/configs/settingsConfig.ts

#187  added version of app section to the settings screen

add version of app section to the settings screen

---

src/configs/eventDetailsConfig.ts

hide info & more label

---

src/components/EventDetailsComponents/components/Synopsis.tsx

#191  filtered synopsis by empty text

filter synopsis by empty text

---

src/components/EventDetailsComponents/components/Cast.tsx
src/components/EventDetailsComponents/components/Creatives.tsx
src/components/EventDetailsComponents/components/General.tsx
src/components/EventDetailsComponents/components/Synopsis.tsx
src/configs/eventDetailsConfig.ts

#186  linked  goDown Label to existed next section

link  goDown Label to existed next section

---

src/components/NavMenu/index.tsx

#195  fixed the problem with getting focus on the exit button when we moved to the nav menu from the last rail

problem with getting focus on exit button

---

src/components/GlobalModal/variants/warningOfExitModal.tsx

fixed problem with losing focus on exit of app modal when pressing the return button of RC

fixed problem with losing focus on exit of app modal

---

src/components/Player/PlayerControls.tsx

#199 199 hide subtitles button for without subtitles videos

hide subtitles button for without subtitles videos

---

src/components/EventDetailsComponents/components/General.tsx
src/components/GlobalModal/variants/continueWatchingModal.tsx

#201  the added handler of return button for continue watching modal

adding handler of return button for continue watching modal

---

src/components/Player/PlayerControls.tsx
src/components/Player/index.tsx
src/configs/playerConfig.ts

#203 video fast-forward and rewind enhancement with long pressing

video fastForward and rewind enhancement with long pressing

---

src/components/SettingsComponents/components/SwitchBetweenEnv.tsx
src/components/SettingsComponents/index.tsx
src/configs/prismicApiConfig.ts
src/configs/settingsConfig.ts
src/screens/SettingsScreen/index.tsx
src/services/apiClient/index.ts
src/services/prismicApiClient/index.ts
src/services/store/index.ts
src/services/store/settings/Selectors.ts
src/services/store/settings/Slices.ts

#206 implemented functionality of changing environment on the fly from the tv app

changing environment on the fly from the tv app

---

package.json
src/components/EventDetailsComponents/components/General.tsx
src/components/GlobalModal/variants/index.tsx
src/components/GlobalModal/variants/rentalStateStatusModal.tsx
src/layouts/appLayout.tsx
src/services/apiClient/index.ts
src/utils/customErrors.ts
src/utils/promiseWait.ts
yarn.lock

#208 shows a modal screen when the rental status is checked. the modal screen shows around 3 seconds

created checking rental flow(modal screen, support method and so on)

---

src/components/Player/PlayerControls.tsx
src/components/Player/index.tsx
src/screens/EventDetailsScreen/index.tsx

https://jira.atlassian.roh.org.uk/browse/RD-7885

RD-7885 Add Overlay Guidance

---

src/components/EventDetailsComponents/commonControls/ExtrasInfoBlock.tsx
src/components/EventDetailsComponents/components/Extras.tsx
src/components/EventDetailsComponents/index.tsx
src/components/GoBack.tsx
src/components/Player/ControlButton.tsx
src/components/Player/PlayerControls.tsx
src/components/ScrollingPagination.tsx
src/configs/eventDetailsConfig.ts

added extras section

---

src/components/EventDetailsComponents/commonControls/ActionButtonList.tsx
src/components/EventDetailsComponents/commonControls/ExtrasInfoBlock.tsx
src/components/EventDetailsComponents/commonControls/MoveToTopSectionButton.tsx
src/components/EventDetailsComponents/commonControls/MultiColumnAboutProductionList.tsx
src/components/EventDetailsComponents/commonControls/MultiColumnRoleNameList.tsx
src/components/EventDetailsComponents/commonControls/MultiColumnSynopsisList.tsx
src/components/EventDetailsComponents/components/AboutProduction.tsx
src/components/EventDetailsComponents/components/Cast.tsx
src/components/EventDetailsComponents/components/Creatives.tsx
src/components/EventDetailsComponents/components/Extras.tsx
src/components/EventDetailsComponents/components/General.tsx
src/components/EventDetailsComponents/components/Synopsis.tsx
src/configs/eventDetailsConfig.ts
src/screens/EventDetailsScreen/index.tsx

#226  add the functionality of moving to the top section from the last available section

add functionality of moving to top section from last available section

---

App.tsx
src/components/EventDetailsComponents/commonControls/ExpandableButton.tsx
src/components/EventDetailsComponents/commonControls/ExtrasVideoButton.tsx
src/components/EventDetailsComponents/components/Extras.tsx
src/components/EventDetailsComponents/components/General.tsx
src/components/GlobalModal/index.tsx
src/components/GlobalModal/variants/index.tsx
src/components/GlobalModal/variants/playerModal.tsx
src/components/Player/ControlButton.tsx
src/components/Player/PlayerControls.tsx
src/components/Player/index.tsx
src/layouts/appLayout.tsx
src/screens/EventDetailsScreen/index.tsx
src/services/tvRCEventListener/index.ts

#238 refactored previous code  for event details info; fixed working remote control for opening any videos

play button on RC for different videos

---

src/components/EventDetailsComponents/commonControls/MultiColumnAboutProductionList.tsx
src/components/EventDetailsComponents/commonControls/MultiColumnRoleNameList.tsx
src/components/EventDetailsComponents/commonControls/MultiColumnSynopsisList.tsx
src/hooks/useSplitingOnColumnsForSynopsis.tsx

#241 fixed synopsis layout and hook for measuring layout for synopsis and about production screens

fixed synopsis layout and hook

---

src/components/EventListComponents/components/DigitalEventItem.tsx
src/components/EventListComponents/components/RailSections.tsx
src/components/NavMenu/index.tsx
src/screens/BalletDanceScreen/index.tsx
src/screens/HomePageScreen/index.tsx
src/screens/OperaMusicScreen/index.tsx

#48 we can try to improve it to endless scrolling from top to bottom direction

added endless scrolling to screens with rails from bottom to top
